import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

// Activate the new service worker as soon as it's installed.
self.skipWaiting();

// Precache all assets defined in self.__WB_MANIFEST (this is injected by VitePWA)
precacheAndRoute(self.__WB_MANIFEST);

// Clean up old caches generated by previous versions of Workbox (and our old CACHE_NAME)
cleanupOutdatedCaches();

// Define a custom cache name for runtime caching (e.g., for APIs or other assets not precached)
const RUNTIME_CACHE_NAME = 'runtime-cache';

// Fallback to network for navigations, then cache.
// This is good for SPAs: always try to get the latest HTML, but fall back to cached shell.
// If you want an offline-first approach for the shell, you might use a CacheFirst strategy for navigations
// after the initial load, or ensure your shell is always served from precache.
// For SPAs, index.html is usually the shell. Workbox precaching handles this.
// We can create a NavigationRoute for SPA fallback more explicitly if needed.
const navigationRoute = new NavigationRoute(new NetworkFirst({
  cacheName: 'navigation-cache', // Separate cache for navigation responses
  plugins: [
    new CacheableResponsePlugin({
      statuses: [0, 200], // Cache opaque responses and successful responses
    }),
  ],
}), {
  // Optionally, specify a denylist or allowlist for navigation routes.
  // For an SPA, you might want all navigations to go through this.
  // Example: denylist: [/\/admin/], allowlist: [/\/app/]
});

registerRoute(navigationRoute);


// Strategy for CSS, JS, and Worker requests (typically part of the precache, but this is a fallback or for non-precached ones)
registerRoute(
  ({ request }) => request.destination === 'style' ||
                   request.destination === 'script' ||
                   request.destination === 'worker',
  new StaleWhileRevalidate({
    cacheName: 'static-resources-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Strategy for images
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({ // Images are often good candidates for CacheFirst
    cacheName: 'image-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      // Optionally, add expiration for images
      // new ExpirationPlugin({
      //   maxEntries: 50,
      //   maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      // }),
    ],
  })
);

// Example: Caching API calls (GET requests) with a NetworkFirst strategy
// registerRoute(
//   ({url}) => url.pathname.startsWith('/api/'),
//   new NetworkFirst({
//     cacheName: 'api-cache',
//     plugins: [
//       new CacheableResponsePlugin({
//         statuses: [0, 200], // Cache successful responses (and opaque if necessary)
//       }),
//       // new ExpirationPlugin({
//       //   maxEntries: 10,
//       //   maxAgeSeconds: 5 * 60, // 5 minutes
//       // })
//     ]
//   })
// );

// Old 'activate' logic for self.clients.claim() is good to ensure the activated SW takes control.
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

// The old fetch listener is replaced by Workbox routes.
// The old install listener's cache.addAll() is replaced by precacheAndRoute.
// The old CACHE_NAME and urlsToCache are no longer needed for precaching.
